name: pachyderm

base:
  # NB: use:
  #     testctl ssh --tty=false -- docker images --format "{{.Repository}}:{{.Tag}}" |sort |sed 's/^/   - /g'
  # to refresh this list
  # (to get extra fancy, highlight the following lines in vim and type :! and then
  # the above command to replace it inline)
  preload_docker_images: []

  # TODO: make this optional
  kernel_image: "quay.io/testfaster/ignite-kernel"

  os_dockerfile: |-
    FROM quay.io/testfaster/kube-ubuntu
    RUN apt-get update && apt-get install -y build-essential gettext-base socat

  prewarm_script: |-
    #!/bin/bash
    set -euo pipefail

    # TODO: switch this back to pachyderm/pachyderm once we land this
    # experiment
    git clone https://github.com/pachyderm/pachyderm-ci-experiment pachyderm
    cd pachyderm

    # pin the version of pachyderm we use for prewarm script, so at least it's
    # reproducible. if pachyderm changes the things being brought up in here,
    # we'll want to bump this hash.
    git checkout 4ad21486691182526c3d03cffb296657b722be4e

    helm version
    make launch-loki

  kubernetes_version: 'v1.18.3'

runtime:
  cpus: 2
  memory: 4GB
  disk: 20GB

prewarm_pool_size: 5
max_pool_size: 15
# timeout vms after 1hr. hopefully tests will clean them up sooner, but if the
# tests themselves timeout and cleanup doesn't get run...
default_lease_timeout: 1h
