name: pachyderm

base:
  # NB: use:
  #     testctl ssh --tty=false -- docker images --format "{{.Repository}}:{{.Tag}}" |sort |sed 's/^/   - /g'
  # to refresh this list
  # (to get extra fancy, highlight the following lines in vim and type :! and then
  # the above command to replace it inline)
  preload_docker_images: []

  # TODO: make this optional
  kernel_image: "quay.io/testfaster/ignite-kernel"

  os_dockerfile: |-
    FROM quay.io/testfaster/kube-ubuntu
    RUN apt-get update && apt-get install -y build-essential gettext-base socat shellcheck

  prewarm_script: |-
    #!/bin/bash
    set -euo pipefail

    # TODO: switch this back to pachyderm/pachyderm once we land this
    # experiment
    git clone https://github.com/pachyderm/pachyderm-ci-experiment pachyderm
    cd pachyderm

    # pin the version of pachyderm we use for prewarm script, so at least it's
    # reproducible. if pachyderm changes the things being brought up in here,
    # we'll want to bump this hash.
    git checkout 2e75668aa915061917d51db33ca9bbe65b7f95df

    make install
    make docker-build

    helm version
    make launch-loki

    # helm
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    chmod +x get_helm.sh
    sudo ./get_helm.sh
    rm ./get_helm.sh # stop shellcheck complaining!

    # kubectl
    sudo curl -sSL -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubectl
    sudo chmod +x /usr/local/bin/kubectl

  kubernetes_version: 'v1.18.3'

runtime:
  cpus: 4
  memory: 4GB
  disk: 20GB

prewarm_pool_size: 24
max_pool_size: 36
# timeout vms after 1hr. hopefully tests will clean them up sooner, but if the
# tests themselves timeout and cleanup doesn't get run...
default_lease_timeout: 1h
