name: pachyderm

base:
  # NB: use:
  #     testctl ssh --tty=false -- docker images --format "{{.Repository}}:{{.Tag}}" |sort |sed 's/^/   - /g'
  # to refresh this list
  # (to get extra fancy, highlight the following lines in vim and type :! and then
  # the above command to replace it inline)
  preload_docker_images: []

  # TODO: make this optional
  kernel_image: "quay.io/testfaster/ignite-kernel"

  os_dockerfile: |-
    FROM quay.io/testfaster/kube-ubuntu

  prewarm_script: |-
    #!/bin/bash
    set -euo pipefail

    git clone https://github.com/pachyderm/pachyderm
    cd pachyderm

    # pin the version of pachyderm we use for prewarm script, so at least it's
    # reproducible. if pachyderm changes the things being updated in here,
    # we'll want to bump this hash.
    git checkout 484178af785f8f6b5c4a6c4d263bbe5f57717333

    make launch-loki

  kubernetes_version: 'v1.17.11'

runtime:
  cpus: 2
  memory: 4GB
  disk: 20GB

prewarm_pool_size: 5
max_pool_size: 15
default_lease_timeout: "" # Never timeout leases, as we use this for dev
