name: pachyderm

base:
  # NB: use:
  #     testctl ssh --tty=false -- docker images --format "{{.Repository}}:{{.Tag}}" |sort |sed 's/^/   - /g'
  # to refresh this list
  # (to get extra fancy, highlight the following lines in vim and type :! and then
  # the above command to replace it inline)
  preload_docker_images:
   - gcr.io/k8s-minikube/storage-provisioner:v1.8.1
   - grafana/loki:2.0.0
   - grafana/promtail:2.0.0
   - k8s.gcr.io/coredns:1.6.7
   - k8s.gcr.io/etcd:3.4.3-0
   - k8s.gcr.io/kube-apiserver:v1.18.3
   - k8s.gcr.io/kube-controller-manager:v1.18.3
   - k8s.gcr.io/kube-proxy:v1.18.3
   - k8s.gcr.io/kube-scheduler:v1.18.3
   - k8s.gcr.io/pause:3.2

  # TODO: make this optional
  kernel_image: "quay.io/testfaster/ignite-kernel"

  os_dockerfile: |-
    FROM quay.io/testfaster/kube-ubuntu
    RUN apt-get update && apt-get install -y build-essential gettext-base socat shellcheck golang-go rsync jq pv silversearcher-ag
    RUN echo "AcceptEnv ENT_ACT_CODE BUCKET PPS_BUCKETS AUTH_BUCKETS GOPROXY" >> /etc/ssh/sshd_config
    # TODO: switch this back to pachyderm/pachyderm once we land this
    # experiment
    WORKDIR /root
    RUN git clone https://github.com/pachyderm/pachyderm-ci-experiment pachyderm
    # warm up go mod cache and go build cache
    RUN cd pachyderm && \
        git checkout afdde5ac0060bc0e9ecdffb74fd09fb53fa52a1e && \
        make install

  docker_bake_script: |-
    #!/bin/bash
    set -xeuo pipefail
    cd /root/pachyderm
    # warm up docker buildkit go mod cache and go build cache
    make docker-build
    # build docker images that are used in PPS tests
    (cd etc/testing/images/ubuntu_with_s3_clients; make image)
    make docker-build-kafka
    echo "============= POST BAKE IMAGES =================="
    docker images
    ls -alh /var/lib/docker
    echo "================================================="

  prewarm_script: |-
    #!/bin/bash
    set -euo pipefail

    cd /root/pachyderm
    ls -alh

    # start services used by tests
    #make launch-loki
    #make launch-dex # XXX doesn't seem to start, need to investigate

  kubernetes_version: 'v1.18.3'

runtime:
  cpus: 16
  memory: 4GB
  disk: 20GB

prewarm_pool_size: 12
max_pool_size: 24
# timeout vms after 1hr. hopefully tests will clean them up sooner, but if the
# tests themselves timeout and cleanup doesn't get run...
default_lease_timeout: 1h
