# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

jobs:
  test:
    docker:
    - image: cimg/base:2020.01

    parameters:
      bucket:
        type: string

    environment:
      PPS_BUCKETS: "6"
      AUTH_BUCKETS: "2"
      GOPROXY: https://proxy.golang.org
      BUCKET: << parameters.bucket >>

    #resource_class: large

    steps:
      - run: |
          sudo apt update && sudo apt install -y pv moreutils rsync

      - checkout

      - run: |
          set -x
          sudo curl -sSL -o /usr/local/bin/testctl https://storage.googleapis.com/get-faster-ci/Linux-x86_64/testctl
          sudo chmod +x /usr/local/bin/testctl
          testctl login --token "$TESTFASTER_TOKEN"

      - run: etc/testing/github_tests.sh 2>&1 |ts

      - run:
          name: Release VM
          command: testctl drop
          when: always

      # retry on failure
      #- run:
      #    name: Test (retry 2)
      #    command: etc/testing/github_tests.sh 2>&1 |ts
      #    when: on_fail

      # retry on failure again...
      #- run:
      #    name: Test (retry 3)
      #    command: etc/testing/github_tests.sh 2>&1 |ts
      #    when: on_fail

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              bucket:
              - MISC
              # If you want to update the number of PPS or auth buckets, you'll neet to
              # update the value of PPS_BUCKETS or AUTH_BUCKETS above
              - ADMIN
              - AUTH1
              - AUTH2
              - PFS
              - PPS1
              - PPS2
              - PPS3
              - PPS4
              - PPS5
              - PPS6
              - EXAMPLES
