# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

jobs:
  test:
    docker:
      # TODO build setup steps below into this
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/pachyderm/pachyderm
    parameters:
      bucket:
        type: string

    environment:
      PPS_BUCKETS: "6"
      AUTH_BUCKETS: "2"
      GOPROXY: https://proxy.golang.org
      BUCKET: << parameters.bucket >>

    steps:
      - checkout

      - run: |
          sudo apt install -y pv shellcheck

      - run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod +x get_helm.sh
          sudo ./get_helm.sh

      - run: |
          set -x
          sudo curl -sSL -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubectl
          sudo chmod +x /usr/local/bin/kubectl

      - run: |
          set -x
          sudo curl -sSL -o /usr/local/bin/testctl https://storage.googleapis.com/get-faster-ci/Linux-x86_64/testctl
          sudo chmod +x /usr/local/bin/testctl
          testctl login --token "$TESTFASTER_TOKEN"

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run: etc/testing/github_tests.sh

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              bucket:
              - MISC
              # If you want to update the number of PPS or auth buckets, you'll neet to
              # update the value of PPS_BUCKETS or AUTH_BUCKETS above
              - ADMIN
              - AUTH1
              - AUTH2
              - PFS
              - PPS1
              - PPS2
              - PPS3
              - PPS4
              - PPS5
              - PPS6
              - EXAMPLES
