name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: self-hosted

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      env:
        DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
      run: etc/testing/github_build.sh

    - uses: azure/setup-kubectl@v1
      id: install

      # TODO: turn this into an action
    - name: Get Testfaster CLI
      run: |
          mkdir -p bin
          curl -sSL -o bin/testctl https://storage.googleapis.com/get-faster-ci/Linux-x86_64/testctl
          chmod +x bin/testctl
          bin/testctl login --token ${{ secrets.TESTFASTER_TOKEN }}
          bin/testctl get
          KUBECONFIG=kubeconfig kubectl get pods --all-namespaces
