name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: self-hosted
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    #- name: Build
    #  env:
    #    DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
    #  run: etc/testing/github_build.sh

    - uses: azure/setup-kubectl@v1
    - uses: azure/setup-helm@v1

    # TODO: turn this into an action
    - name: Get Testfaster CLI
      run: |
          mkdir -p bin
          curl -sSL -o bin/testctl https://storage.googleapis.com/get-faster-ci/Linux-x86_64/testctl
          chmod +x bin/testctl
          echo "$(pwd)/bin" >> $GITHUB_PATH
          bin/testctl login --token ${{ secrets.TESTFASTER_TOKEN }}

    - name: Test
      # Send stderr to stdout to try and avoid interleaving stdout and stderr
      # bug in github actions. They're indistinguishable anyway.
      run: etc/testing/github_tests.sh 2>&1
      env:
        PPS_BUCKETS: 6
        AUTH_BUCKETS: 2
        GOPROXY: https://proxy.golang.org
        BUCKET: ${{ matrix.bucket }}

    strategy:
      matrix:
        bucket:
        - MISC
        # If you want to update the number of PPS or auth buckets, you'll neet to
        # update the value of PPS_BUCKETS or AUTH_BUCKETS above
        - ADMIN
        - AUTH1
        - AUTH2
        - PFS
        - PPS1
        - PPS2
        - PPS3
        - PPS4
        - PPS5
        - PPS6
        - EXAMPLES
